const attribute = [
  "Product_ID",
  "SKU",
  "Name",
  "Product_URL",
  "Price",
  "Retail_Price",
  "Thumbnail_URL",
  "Search_Keywords",
  "Description",
  "Category",
  "Category_ID",
  "Brand",
  "Child_SKU",
  "Child_Price",
  "Color",
  "Color_Family",
  "Color_Swatches",
  "Size",
  "Shoe_Size",
  "Pants_Size",
  "Occassion",
  "Season",
  "Badges",
  "Rating_Avg",
  "Rating_Count",
  "Inventory_Count",
  "Date_Created",
];

module.exports = { attribute };
